<a href="https://colab.research.google.com/github/syedadilejazz/DBSCAN-Algorithm/blob/master/Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
#Connect colab to GoogleDrive

In [6]:
# from google.colab import drive
# drive.mount('/content/drive')

In [7]:
import os
os.getcwd()

'/Users/syedadilejaz/Complete_GenAI_Series_Bappy_euron'

In [8]:
#df = pd.read_csv('/Users/syedadilejaz/data/IMDB Dataset.csv', escapechar='\\', quotechar='"')

df=pd.read_csv('data/IMDB Dataset 2.csv', escapechar='\\', quotechar='"')
print("Shape",df.shape)
print("Columns",df.columns)
df.head(3)

Shape (50000, 2)
Columns Index(['review', 'sentiment'], dtype='object')

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [9]:
# from google.colab import drive
# drive.mount('/content/drive')

Lower Case

In [10]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [11]:
df["review"]=df["review"].apply(lambda x:x.lower())
df["sentiment"]=df["sentiment"].apply(lambda x:x.lower())
df.head(3)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive

remove_html_tags

In [12]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    """
    < matched opening angle bracket
    .*? matched any character(.),any number of time(*),but non-greedy(?)
    > matched closing angle bracket
    """
    return pattern.sub(r'', text)#Replaces everything that matched the pattern with empty string

In [13]:
text = "<html><body><p>Movie 1</pppppppppp><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [14]:
remove_html_tags(text)

'Movie 1 Actor - Aamir Khan Click here to download'

In [15]:
df['review'] = df['review'].apply(remove_html_tags)

In [16]:
df["review"][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

remove_url

In [17]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [18]:
text1 = 'Check out my youtube http://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

In [19]:
remove_url(text1)

'Check out my youtube  dswithbappy'

In [20]:
df['review'] = df['review'].apply(remove_url)

punctuation handling

In [21]:
import string,time
exclude=string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [22]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [23]:
text = 'string. With.@!#$%^&*()_+ Punctuation?'

In [24]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
2.658367156982422

In [25]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [26]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

1.6570091247558594

In [27]:
time1/time2

1.60431654676259

In [28]:
df["review"][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [29]:
df["review"]=df["review"].apply(remove_punc)
df["review"][5]

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

chat_conversion handle

In [30]:

chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible',




    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

In [31]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [32]:
chat_conversion('Do this work FYA')

'Do this work For Your Action'

In [33]:
df["review"]=df["review"].apply(chat_conversion)

incorrect_text handling

In [34]:
#!pip3 install textblob
from textblob import TextBlob

In [35]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner. hindiiii bolo'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner. hindiiii bold'

In [36]:
def incorrect_text_func(incorrect_text):
    textBlb = TextBlob(incorrect_text)
    return textBlb.correct().string

# safer: keep original and write fixes to a new column
df["review_fixed"] = df["review"]
df.loc[0:99, "review_fixed"] = df.loc[0:99, "review_fixed"].apply(incorrect_text_func)#2 mins

In [37]:
# ...existing code...
import sys
!{sys.executable} -m pip install -q pyspellchecker joblib

from spellchecker import SpellChecker
from joblib import Parallel, delayed

spell = SpellChecker(distance=1)  # distance=1 is fast; increase if needed

def quick_spell_fix(text):
    if not isinstance(text, str) or not text.strip():
        return text
    out = []
    for w in text.split():
        if w.isalpha():
            # keep case of original token (lower for lookup)
            cand = spell.correction(w.lower())
            out.append(cand if cand is not None else w)
        else:
            out.append(w)
    return " ".join(out)

# Test on small sample
df["review_fixed_spell"] = df["review"]
df.loc[0:99, "review_fixed_spell"] = df.loc[0:99, "review_fixed_spell"].apply(incorrect_text_func)

In [38]:
(df.loc[0:99, "review_fixed"] == df.loc[0:99, "review_fixed_spell"]).all()

True

stopwords

In [39]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/syedadilejaz/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [40]:
stopwrds=(list(stopwords.words('english')))
print("Stopwords lenghth",len(stopwrds))
print(stopwrds[0:10])

Stopwords lenghth 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']

In [41]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [42]:
df.loc[0:99,"review"] = df.loc[0:99,"review"].apply(remove_stopwords)

In [43]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [44]:
df["review"][10]

'phil  alien  one   quirky films   humour  based around  oddness  everything rather  actual punchlinesat first    odd  pretty funny    movie progressed  didnt find  jokes  oddness funny anymoreits  low budget film thats never  problem      pretty interesting characters  eventually   lost interesti imagine  film would appeal   stoner   currently partakingfor something similar  better try brother  another planet'

In [45]:
test=remove_stopwords(df["review"][10])
test

'phil alien one quirky films humour based around oddness everything rather actual punchlinesat first odd pretty funny movie progressed didnt find jokes oddness funny anymoreits low budget film thats never problem pretty interesting characters eventually lost interesti imagine film would appeal stoner currently partakingfor something similar better try brother another planet'

In [46]:
" ".join(set(df["review"][10].split()).symmetric_difference(set(test.split())))

''

remove_emoji handle

In [47]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [48]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [49]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [50]:
!pip install emoji

Requirement already satisfied: emoji in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (2.15.0)

In [51]:
# show notebook kernel/python path (pure Python)
import sys
print(sys.executable, sys.version)

/Users/syedadilejaz/anaconda3/bin/python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

In [52]:
# run the same as a shell command from the notebook kernel
!python -c "import sys; print(sys.executable, sys.version)"

/Users/syedadilejaz/anaconda3/bin/python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

In [53]:
# install emoji into the exact kernel interpreter (preferred for notebook)
import sys
!{sys.executable} -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org emoji

Requirement already satisfied: emoji in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (2.15.0)

In [54]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [55]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

Tokenization

1. Using the split function

In [56]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [57]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [58]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [59]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

2. Regular Expression

In [60]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [61]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

3. NLTK

In [62]:
# ...existing code...
import nltk
nltk.download('punkt_tab', quiet=True)   # ensure punkt is available
from nltk.tokenize import word_tokenize, sent_tokenize

sent1 = 'I am going to visit delhi!'
print(word_tokenize(sent1))
# ...existing code...

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [63]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [64]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [65]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [66]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

4. Spacy (good)

In [67]:
!pip3 install spacy

Requirement already satisfied: spacy in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.24.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (68.0.0)
Requirement already satisfied: packaging>=20.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (23.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from jinja2->spacy) (2.1.1)
Requirement already satisfied: anyio in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (3.5.0)
Requirement already satisfied: httpcore==1.* in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.2.0)

In [68]:
%pip install -U typing_extensions spacy

Requirement already satisfied: typing_extensions in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (4.15.0)
Requirement already satisfied: spacy in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.24.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (68.0.0)
Requirement already satisfied: packaging>=20.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (23.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from jinja2->spacy) (2.1.1)
Requirement already satisfied: anyio in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (3.5.0)
Requirement already satisfied: httpcore==1.* in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [69]:
import sys 
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 4.7 MB/s eta 0:00:0000:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [70]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [71]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [72]:
doc4 = nlp(sent1)
doc4

I am going to visit delhi!

In [73]:
for token in doc4:
    print(token)

I
am
going
to
visit
delhi
!

In [74]:
df.head()

,review,sentiment,review_fixed,review_fixed_spell
0,one reviewers mentioned watching 1 oz e...,positive,one of the other reviews has mentioned that af...,one of the other reviews has mentioned that af...
1,wonderful little production filming techniqu...,positive,a wonderful little production the filling tech...,a wonderful little production the filling tech...
2,thought wonderful way spend time hot s...,positive,i thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,basically theres family little boy jake thi...,negative,basically there a family where a little boy ja...,basically there a family where a little boy ja...
4,petter matteis love time money visually s...,positive,letter matters love in the time of money is a ...,letter matters love in the time of money is a ...

Stemmer

In [75]:
from nltk.stem.porter import PorterStemmer

In [76]:

ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [77]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [78]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [79]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

Lemmatization

In [80]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/syedadilejaz/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/syedadilejaz/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

NOTE: Stemming & lamatization are same to retrieve root words but lamatization is worked good. Lamatization is slow & stemming is fast

Bag of words

In [81]:
import numpy as np
import pandas as pd

In [82]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

OneHot Encoding

In [86]:
list=[]
for i in df["text"]:
    temp=i.split()
    for j in temp:
        if j in list:
            pass
        else:
            list.append(j)
list

['people', 'watch', 'dswithbappy', 'write', 'comment']

In [90]:
onehot_df=pd.get_dummies(list).astype(int)
onehot_df

   comment  dswithbappy  people  watch  write
0        0            0       1      0      0
1        0            0       0      1      0
2        0            1       0      0      0
3        0            0       0      0      1
4        1            0       0      0      0

OneHot Encoding can be also done by Sklearn OneHotEncoder

Bag of Words

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [92]:
bow = cv.fit_transform(df['text'])

In [93]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [94]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [95]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]

In [99]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [101]:
X = bow.toarray()
y = df['output']
print(X,y)

[[0 1 1 1 0]
 [0 2 0 1 0]
 [1 0 1 0 1]
 [1 1 0 0 1]] 0    1
1    1
2    0
3    0
Name: output, dtype: int64

In [104]:
print(cv.get_feature_names_out())
pd.DataFrame(bow.toarray(),columns=cv.get_feature_names_out())

['comment' 'dswithbappy' 'people' 'watch' 'write']

   comment  dswithbappy  people  watch  write
0        0            1       1      1      0
1        0            2       0      1      0
2        1            0       1      0      1
3        1            1       0      0      1

N-grams

In [105]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [106]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [107]:
bow = cv.fit_transform(df['text'])

In [108]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}

In [109]:
print(cv.get_feature_names_out())

['dswithbappy watch' 'dswithbappy write' 'people watch' 'people write'
 'watch dswithbappy' 'write comment']

In [110]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]

In [111]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [112]:
bow = cv.fit_transform(df['text'])

In [113]:
cv.vocabulary_

{'people watch dswithbappy': 2,
 'dswithbappy watch dswithbappy': 0,
 'people write comment': 3,
 'dswithbappy write comment': 1}

In [115]:
cv.get_feature_names_out()

array(['dswithbappy watch dswithbappy', 'dswithbappy write comment',
       'people watch dswithbappy', 'people write comment'], dtype=object)

In [116]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]

TF-IDF (Term frequency- Inverse document frequency)

In [117]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [118]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
tfid.get_feature_names_out()

array(['comment', 'dswithbappy', 'people', 'watch', 'write'], dtype=object)

In [126]:
arr=tfid.fit_transform(df['text'])

In [128]:
print(arr[0].toarray())
print(arr[1].toarray())
print(arr[2].toarray())

[[0.         0.49681612 0.61366674 0.61366674 0.        ]]
[[0.         0.8508161  0.         0.52546357 0.        ]]
[[0.57735027 0.         0.57735027 0.         0.57735027]]

In [130]:
arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [135]:
print(tfid.get_feature_names_out()  )
print(tfid.idf_)

['comment' 'dswithbappy' 'people' 'watch' 'write']
[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]

In [136]:
dict(zip(tfid.get_feature_names_out(),tfid.idf_))

{'comment': 1.5108256237659907,
 'dswithbappy': 1.2231435513142097,
 'people': 1.5108256237659907,
 'watch': 1.5108256237659907,
 'write': 1.5108256237659907}

#Rear word is having high weights/values

Word2Vec

In [145]:
import numpy as np
import pandas as pd
import gensim
import os

In [146]:
!pip install --upgrade gensim --user

Requirement already satisfied: gensim in /Users/syedadilejaz/.local/lib/python3.11/site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from gensim) (1.24.3)
Requirement already satisfied: scipy>=1.7.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from gensim) (1.11.1)
Requirement already satisfied: smart_open>=1.8.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from gensim) (5.2.1)

In [147]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab', quiet=True)   # ensure punkt is available

True

In [148]:
#Example
#Steps-Converts to lowercase,Remove Punctuation,Tokenizes,Remove very short words.
text="I love NLP! It's amazing."
tokens=simple_preprocess(text)
print(tokens)

['love', 'nlp', 'it', 'amazing']

In [149]:
story = []
for filename in os.listdir('data'):
    print("filename",filename)
    if filename == '.ipynb_checkpoints':
      pass
    f = open(os.path.join('data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    print("raw_sent",raw_sent[0:5])
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

filename IMDB Dataset 2.csv
raw_sent ['review,sentiment\n"One of the other reviewers has mentioned that after watching just 1 Oz episode you\'ll be hooked.', 'They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO.', 'Trust me, this is not a show for the faint hearted or timid.', 'This show pulls no punches with regards to drugs, sex or violence.', 'Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary.']

In [151]:
story[0:5]

[['review',
  'sentiment',
  'one',
  'of',
  'the',
  'other',
  'reviewers',
  'has',
  'mentioned',
  'that',
  'after',
  'watching',
  'just',
  'oz',
  'episode',
  'you',
  'll',
  'be',
  'hooked'],
 ['they',
  'are',
  'right',
  'as',
  'this',
  'is',
  'exactly',
  'what',
  'happened',
  'with',
  'me',
  'br',
  'br',
  'the',
  'first',
  'thing',
  'that',
  'struck',
  'me',
  'about',
  'oz',
  'was',
  'its',
  'brutality',
  'and',
  'unflinching',
  'scenes',
  'of',
  'violence',
  'which',
  'set',
  'in',
  'right',
  'from',
  'the',
  'word',
  'go'],
 ['trust',
  'me',
  'this',
  'is',
  'not',
  'show',
  'for',
  'the',
  'faint',
  'hearted',
  'or',
  'timid'],
 ['this',
  'show',
  'pulls',
  'no',
  'punches',
  'with',
  'regards',
  'to',
  'drugs',
  'sex',
  'or',
  'violence'],
 ['its',
  'is',
  'hardcore',
  'in',
  'the',
  'classic',
  'use',
  'of',
  'the',
  'word',
  'br',
  'br',
  'it',
  'is',
  'called',
  'oz',
  'as',
  'that',
  'is',
  'the',
  'nickname',
  'given',
  'to',
  'the',
  'oswald',
  'maximum',
  'security',
  'state',
  'penitentary']]

In [154]:
model = gensim.models.Word2Vec(
    window=10,#how many words on each side are considered as context
    min_count=2#ignore words with total frequency lower than this
)

In [155]:
model.build_vocab(story)

In [156]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(42741452, 56132345)

In [157]:
model.wv.most_similar('movie')

[('film', 0.9022250771522522),
 ('flick', 0.7103150486946106),
 ('movies', 0.6299260258674622),
 ('it', 0.6172680258750916),
 ('show', 0.5682815909385681),
 ('picture', 0.5396584272384644),
 ('documentary', 0.5330386757850647),
 ('series', 0.5221733450889587),
 ('films', 0.5216909646987915),
 ('episode', 0.5070165395736694)]

In [161]:
model.wv.similarity('movie','series')

0.5221733

In [162]:
model.wv['deep'].shape

(100,)

In [163]:
vec = model.wv.get_normed_vectors()
vec

array([[-0.00785689,  0.03847434, -0.05384599, ..., -0.09220313,
        -0.03626863, -0.03672776],
       [ 0.07281243,  0.08281672, -0.07319538, ..., -0.03398868,
        -0.11435076, -0.05289366],
       [-0.05282364,  0.12599856, -0.0218786 , ...,  0.0393212 ,
         0.13688098, -0.02115712],
       ...,
       [-0.10217645,  0.29490376,  0.03435528, ..., -0.15852748,
         0.12577602, -0.05645187],
       [ 0.00232888,  0.14377968,  0.10578293, ..., -0.01043732,
         0.10405381, -0.04536634],
       [-0.05417769,  0.18718386,  0.11609823, ..., -0.06110939,
         0.05790873,  0.00940153]], dtype=float32)

In [164]:
model.wv.get_normed_vectors().shape

(62093, 100)

In [166]:
y = model.wv.index_to_key
y

['the',
 'and',
 'of',
 'to',
 'is',
 'br',
 'it',
 'in',
 'this',
 'that',
 'was',
 'as',
 'movie',
 'for',
 'with',
 'but',
 'film',
 'you',
 'on',
 'not',
 'he',
 'are',
 'his',
 'have',
 'one',
 'be',
 'all',
 'at',
 'they',
 'by',
 'an',
 'who',
 'so',
 'from',
 'like',
 'there',
 'or',
 'just',
 'her',
 'out',
 'about',
 'if',
 'has',
 'what',
 'some',
 'good',
 'can',
 'when',
 'more',
 'very',
 'she',
 'up',
 'positive',
 'negative',
 'no',
 'time',
 'my',
 'even',
 'would',
 'which',
 'only',
 'story',
 'really',
 'see',
 'their',
 'had',
 'me',
 'well',
 'we',
 'were',
 'than',
 'much',
 'bad',
 'get',
 'been',
 'other',
 'do',
 'people',
 'great',
 'will',
 'also',
 'into',
 'because',
 'how',
 'don',
 'him',
 'first',
 'most',
 'made',
 'its',
 'them',
 'then',
 'make',
 'way',
 'could',
 'too',
 'movies',
 'any',
 'after',
 'characters',
 'think',
 'watch',
 'character',
 'films',
 'two',
 'many',
 'seen',
 'being',
 'love',
 'plot',
 'never',
 'life',
 'acting',
 'where',
 'show',
 'did',
 'best',
 'know',
 'little',
 'over',
 'off',
 'ever',
 'man',
 'does',
 'your',
 'better',
 'end',
 'here',
 'scene',
 'still',
 'say',
 'these',
 'why',
 'scenes',
 'while',
 've',
 'something',
 'such',
 'go',
 'should',
 'through',
 'back',
 'real',
 'those',
 'now',
 'thing',
 'watching',
 'actors',
 're',
 'doesn',
 'director',
 'didn',
 'years',
 'funny',
 'though',
 'old',
 'another',
 'work',
 'before',
 'actually',
 'nothing',
 'makes',
 'look',
 'find',
 'going',
 'new',
 'same',
 'lot',
 'every',
 'few',
 'part',
 'again',
 'world',
 'down',
 'cast',
 'us',
 'things',
 'want',
 'quite',
 'pretty',
 'horror',
 'around',
 'seems',
 'young',
 'take',
 'big',
 'however',
 'got',
 'thought',
 'fact',
 'enough',
 'long',
 'both',
 'give',
 'may',
 'own',
 'between',
 'comedy',
 'series',
 'must',
 'right',
 'action',
 'music',
 'without',
 'guy',
 'times',
 'saw',
 'original',
 'always',
 'isn',
 'role',
 'come',
 'almost',
 'gets',
 'point',
 'interesting',
 'done',
 'whole',
 'least',
 'far',
 'bit',
 'script',
 'family',
 'minutes',
 'feel',
 'll',
 'might',
 'am',
 'making',
 'anything',
 'since',
 'tv',
 'last',
 'probably',
 'performance',
 'kind',
 'away',
 'girl',
 'yet',
 'fun',
 'anyone',
 'woman',
 'worst',
 'sure',
 'rather',
 'hard',
 'day',
 'each',
 'played',
 'found',
 'looking',
 'screen',
 'our',
 'although',
 'especially',
 'believe',
 'dvd',
 'having',
 'trying',
 'course',
 'everything',
 'set',
 'goes',
 'book',
 'ending',
 'put',
 'comes',
 'maybe',
 'place',
 'let',
 'shows',
 'three',
 'worth',
 'different',
 'actor',
 'once',
 'main',
 'sense',
 'someone',
 'american',
 'reason',
 'play',
 'effects',
 'looks',
 'true',
 'money',
 'watched',
 'wasn',
 'year',
 'everyone',
 'job',
 'together',
 'war',
 'high',
 'plays',
 'audience',
 'instead',
 'during',
 'half',
 'said',
 'later',
 'takes',
 'special',
 'john',
 'night',
 'seem',
 'beautiful',
 'left',
 'black',
 'himself',
 'seeing',
 'wife',
 'version',
 'shot',
 'excellent',
 'house',
 'idea',
 'star',
 'else',
 'mind',
 'death',
 'fan',
 'father',
 'used',
 'nice',
 'budget',
 'simply',
 'poor',
 'short',
 'completely',
 'second',
 'men',
 'read',
 'less',
 'along',
 'top',
 'home',
 'dead',
 'help',
 'line',
 'hollywood',
 'either',
 'kids',
 'boring',
 'friends',
 'camera',
 'production',
 'try',
 'wrong',
 'enjoy',
 'classic',
 'low',
 'use',
 'given',
 'women',
 'need',
 'full',
 'school',
 'stupid',
 'next',
 'until',
 'performances',
 'rest',
 'truly',
 'couple',
 'video',
 'awful',
 'sex',
 'start',
 'recommend',
 'tell',
 'terrible',
 'mean',
 'remember',
 'getting',
 'came',
 'won',
 'understand',
 'perhaps',
 'name',
 'moments',
 'face',
 'person',
 'keep',
 'itself',
 'human',
 'wonderful',
 'mother',
 'playing',
 'style',
 'episode',
 'small',
 'others',
 'boy',
 'perfect',
 'stars',
 'early',
 'doing',
 'head',
 'often',
 'written',
 'definitely',
 'lines',
 'children',
 'dialogue',
 'gives',
 'piece',
 'couldn',
 'went',
 'case',
 'finally',
 'yes',
 'title',
 'absolutely',
 'live',
 'laugh',
 'oh',
 'certainly',
 'friend',
 'lost',
 'liked',
 'become',
 'entertaining',
 'worse',
 'sort',
 'cinema',
 'picture',
 'loved',
 'called',
 'hope',
 'felt',
 'mr',
 'overall',
 'guys',
 'based',
 'entire',
 'several',
 'supposed',
 'drama',
 'sound',
 'problem',
 'white',
 'against',
 'waste',
 'beginning',
 'dark',
 'fans',
 'game',
 'totally',
 'care',
 'humor',
 'direction',
 'wanted',
 'under',
 'seemed',
 'evil',
 'lives',
 'lead',
 'despite',
 'guess',
 'example',
 'final',
 'turn',
 'already',
 'throughout',
 'becomes',
 'killer',
 'unfortunately',
 'able',
 'son',
 'quality',
 'days',
 'history',
 'heart',
 'side',
 'fine',
 'michael',
 'flick',
 'wants',
 'writing',
 'horrible',
 'amazing',
 'run',
 'today',
 'art',
 'town',
 'act',
 'works',
 'close',
 'kill',
 'god',
 'child',
 'matter',
 'etc',
 'tries',
 'viewer',
 'past',
 'genre',
 'enjoyed',
 'turns',
 'brilliant',
 'behind',
 'gave',
 'car',
 'stuff',
 'eyes',
 'parts',
 'favorite',
 'girls',
 'directed',
 'hand',
 'kid',
 'late',
 'city',
 'hour',
 'expect',
 'soon',
 'actress',
 'themselves',
 'obviously',
 'sometimes',
 'thinking',
 'killed',
 'myself',
 'starts',
 'decent',
 'stop',
 'type',
 'self',
 'daughter',
 'highly',
 'group',
 'says',
 'blood',
 'voice',
 'anyway',
 'writer',
 'took',
 'known',
 'heard',
 'happens',
 'except',
 'fight',
 'feeling',
 'experience',
 'coming',
 'slow',
 'moment',
 'stories',
 'leave',
 'police',
 'told',
 'score',
 'extremely',
 'violence',
 'hero',
 'involved',
 'strong',
 'chance',
 'lack',
 'ok',
 'hit',
 'hilarious',
 'cannot',
 'roles',
 'happen',
 'wouldn',
 'wonder',
 'living',
 'particularly',
 'including',
 'hell',
 'save',
 'brother',
 'crap',
 'murder',
 'looked',
 'cool',
 'david',
 'please',
 'simple',
 'age',
 'cut',
 'obvious',
 'song',
 'complete',
 'gore',
 'happened',
 'serious',
 'james',
 'attempt',
 'ago',
 'shown',
 'taken',
 'robert',
 'husband',
 'english',
 'reality',
 'seriously',
 'released',
 'jokes',
 'opening',
 'interest',
 'none',
 'alone',
 'across',
 'sad',
 'possible',
 'exactly',
 'career',
 'hours',
 'number',
 'saying',
 'usually',
 'talent',
 'cinematography',
 'view',
 'documentary',
 'relationship',
 'annoying',
 'running',
 'yourself',
 'order',
 'wish',
 'huge',
 'shots',
 'whose',
 'body',
 'light',
 'taking',
 'country',
 'ridiculous',
 'power',
 'important',
 'middle',
 'call',
 'female',
 'level',
 'ends',
 'started',
 'major',
 'four',
 'word',
 'turned',
 'jack',
 'opinion',
 'change',
 'scary',
 'mostly',
 'usual',
 'room',
 'beyond',
 'ones',
 'happy',
 'silly',
 'rating',
 'somewhat',
 'novel',
 'words',
 'talking',
 'knows',
 'knew',
 'disappointed',
 'strange',
 'apparently',
 'non',
 'modern',
 'upon',
 'attention',
 'single',
 'basically',
 'cheap',
 'finds',
 'television',
 'musical',
 'due',
 'earth',
 'problems',
 'miss',
 'episodes',
 'clearly',
 'local',
 'thriller',
 'king',
 'five',
 'british',
 'talk',
 'class',
 'events',
 'sequence',
 'aren',
 'team',
 'french',
 'moving',
 'ten',
 'fast',
 'review',
 'tells',
 'straight',
 'predictable',
 'die',
 'entertainment',
 'comic',
 'songs',
 'space',
 'whether',
 'george',
 'future',
 'dialog',
 'add',
 'above',
 'sets',
 'easily',
 'near',
 'enjoyable',
 'appears',
 'haven',
 'soundtrack',
 'hate',
 'bring',
 'romantic',
 'giving',
 'lots',
 'similar',
 'supporting',
 'message',
 'release',
 'eye',
 'mention',
 'within',
 'filmed',
 'sequel',
 'falls',
 'rock',
 'sister',
 'monster',
 'clear',
 'needs',
 'dull',
 'bunch',
 'suspense',
 'surprised',
 'easy',
 'showing',
 'sorry',
 'tried',
 'certain',
 'working',
 'ways',
 'theater',
 'theme',
 'parents',
 'among',
 'named',
 'storyline',
 'lady',
 'stay',
 'fall',
 'effort',
 'stand',
 'minute',
 'gone',
 'feature',
 'dr',
 'buy',
 'tale',
 'dog',
 'using',
 'typical',
 'comments',
 'mystery',
 'editing',
 'th',
 'avoid',
 'subject',
 'deal',
 'oscar',
 'doubt',
 'richard',
 'peter',
 'okay',
 'fantastic',
 'viewers',
 'realistic',
 'feels',
 'kept',
 'nearly',
 'general',
 'check',
 'viewing',
 'elements',
 'points',
 'greatest',
 'herself',
 'means',
 'famous',
 'crime',
 'rent',
 'imagine',
 'paul',
 'red',
 'form',
 'actual',
 'follow',
 'period',
 'material',
 'believable',
 'tom',
 'move',
 'brought',
 'forget',
 'somehow',
 'begins',
 'animation',
 'reviews',
 'leads',
 'doctor',
 'imdb',
 'surprise',
 'figure',
 'america',
 'weak',
 'hear',
 'sit',
 'average',
 'open',
 'york',
 'deep',
 'fi',
 'sequences',
 'killing',
 'atmosphere',
 'wait',
 'eventually',
 'learn',
 'premise',
 'sci',
 'whatever',
 'expected',
 'dance',
 'boys',
 'lame',
 'indeed',
 'poorly',
 'particular',
 'note',
 'box',
 'truth',
 'situation',
 'hot',
 'shame',
 'third',
 'season',
 'society',
 'free',
 'decided',
 'difficult',
 'lee',
 'romance',
 'needed',
 'acted',
 'crew',
 'gay',
 'leaves',
 'sexual',
 'western',
 'emotional',
 'unless',
 'possibly',
 'footage',
 'de',
 'credits',
 'write',
 'forced',
 'memorable',
 'became',
 'reading',
 'begin',
 'air',
 'otherwise',
 'meet',
 'question',
 'male',
 'street',
 'nature',
 'beauty',
 'meets',
 'hands',
 'plus',
 'cheesy',
 'screenplay',
 'masterpiece',
 'superb',
 'features',
 'effect',
 'stage',
 'interested',
 'island',
 'whom',
 'perfectly',
 'laughs',
 'comment',
 'cop',
 'forward',
 'weird',
 'badly',
 'nor',
 'japanese',
 'previous',
 'inside',
 'sounds',
 'personal',
 'quickly',
 'total',
 'crazy',
 'baby',
 'mark',
 'keeps',
 'disney',
 'girlfriend',
 'result',
 'towards',
 'writers',
 'battle',
 'fire',
 'worked',
 'joe',
 'setting',
 'background',
 'incredibly',
 'earlier',
 'mess',
 'copy',
 'business',
 'dumb',
 'bill',
 'unique',
 'realize',
 'directors',
 'powerful',
 'water',
 'dramatic',
 'rate',
 'older',
 'joke',
 'dream',
 'following',
 'pay',
 'plenty',
 'directing',
 'ask',
 'various',
 'creepy',
 'development',
 'appear',
 'front',
 'brings',
 'rich',
 'admit',
 'political',
 'cover',
 'apart',
 'leading',
 'fairly',
 'spent',
 'reasons',
 'portrayed',
 'era',
 'gun',
 'outside',
 'telling',
 'present',
 'party',
 'wasted',
 'zombie',
 'fighting',
 'william',
 'fails',
 'deserves',
 'success',
 'break',
 'twist',
 'meant',
 'list',
 'secret',
 'return',
 'create',
 'expecting',
 'ideas',
 'attempts',
 'missing',
 'manages',
 'ended',
 'recently',
 'cute',
 'agree',
 'villain',
 'german',
 'match',
 'fantasy',
 ...]

In [167]:
from sklearn.decomposition import PCA

In [168]:
pca = PCA(n_components=3)
X = pca.fit_transform(model.wv.get_normed_vectors())
X

array([[ 7.2128034e-01, -6.9942370e-02, -5.4470275e-04],
       [ 5.7312751e-01,  5.8417350e-02,  9.7363237e-03],
       [ 5.6541806e-01, -1.4359848e-01, -1.1447528e-01],
       ...,
       [ 5.2893078e-01, -2.4610232e-01, -2.6269919e-01],
       [-1.1551688e-01, -1.8223676e-01, -1.4916046e-01],
       [-2.2063473e-01,  1.3778441e-01,  5.7402007e-02]], dtype=float32)

In [169]:
X.shape

(62093, 3)

In [170]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()