<a href="https://colab.research.google.com/github/syedadilejazz/DBSCAN-Algorithm/blob/master/Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
#Connect colab to GoogleDrive

In [6]:
# from google.colab import drive
# drive.mount('/content/drive')

In [7]:
import os
os.getcwd()

'/Users/syedadilejaz/Complete_GenAI_Series_Bappy_euron'

In [8]:
#df = pd.read_csv('/Users/syedadilejaz/data/IMDB Dataset.csv', escapechar='\\', quotechar='"')

df=pd.read_csv('data/IMDB Dataset 2.csv', escapechar='\\', quotechar='"')
print("Shape",df.shape)
print("Columns",df.columns)
df.head(3)

Shape (50000, 2)
Columns Index(['review', 'sentiment'], dtype='object')

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [9]:
# from google.colab import drive
# drive.mount('/content/drive')

Lower Case

In [10]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [11]:
df["review"]=df["review"].apply(lambda x:x.lower())
df["sentiment"]=df["sentiment"].apply(lambda x:x.lower())
df.head(3)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive

remove_html_tags

In [12]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    """
    < matched opening angle bracket
    .*? matched any character(.),any number of time(*),but non-greedy(?)
    > matched closing angle bracket
    """
    return pattern.sub(r'', text)#Replaces everything that matched the pattern with empty string

In [13]:
text = "<html><body><p>Movie 1</pppppppppp><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [14]:
remove_html_tags(text)

'Movie 1 Actor - Aamir Khan Click here to download'

In [15]:
df['review'] = df['review'].apply(remove_html_tags)

In [16]:
df["review"][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

remove_url

In [17]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [18]:
text1 = 'Check out my youtube http://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

In [19]:
remove_url(text1)

'Check out my youtube  dswithbappy'

In [20]:
df['review'] = df['review'].apply(remove_url)

punctuation handling

In [21]:
import string,time
exclude=string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [22]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [23]:
text = 'string. With.@!#$%^&*()_+ Punctuation?'

In [24]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
2.658367156982422

In [25]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [26]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

1.6570091247558594

In [27]:
time1/time2

1.60431654676259

In [28]:
df["review"][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [29]:
df["review"]=df["review"].apply(remove_punc)
df["review"][5]

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

chat_conversion handle

In [30]:

chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible',




    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

In [31]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [32]:
chat_conversion('Do this work FYA')

'Do this work For Your Action'

In [33]:
df["review"]=df["review"].apply(chat_conversion)

incorrect_text handling

In [34]:
#!pip3 install textblob
from textblob import TextBlob

In [35]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner. hindiiii bolo'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner. hindiiii bold'

In [ ]:
def incorrect_text_func(incorrect_text):
    textBlb = TextBlob(incorrect_text)
    return textBlb.correct().string

# safer: keep original and write fixes to a new column
df["review_fixed"] = df["review"]
df.loc[0:99, "review_fixed"] = df.loc[0:99, "review_fixed"].apply(incorrect_text_func)#2 mins

In [ ]:
# ...existing code...
import sys
!{sys.executable} -m pip install -q pyspellchecker joblib

from spellchecker import SpellChecker
from joblib import Parallel, delayed

spell = SpellChecker(distance=1)  # distance=1 is fast; increase if needed

def quick_spell_fix(text):
    if not isinstance(text, str) or not text.strip():
        return text
    out = []
    for w in text.split():
        if w.isalpha():
            # keep case of original token (lower for lookup)
            cand = spell.correction(w.lower())
            out.append(cand if cand is not None else w)
        else:
            out.append(w)
    return " ".join(out)

# Test on small sample
df["review_fixed_spell"] = df["review"]
df.loc[0:99, "review_fixed_spell"] = df.loc[0:99, "review_fixed_spell"].apply(incorrect_text_func)

In [ ]:
(df.loc[0:99, "review_fixed"] == df.loc[0:99, "review_fixed_spell"]).all()

True

stopwords

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 8] nodename
[nltk_data]     nor servname provided, or not known>

False

In [ ]:
stopwrds=(list(stopwords.words('english')))
print("Stopwords lenghth",len(stopwrds))
print(stopwrds[0:10])

Stopwords lenghth 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an']

In [ ]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [ ]:
df.loc[0:99,"review"] = df.loc[0:99,"review"].apply(remove_stopwords)

In [ ]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [ ]:
df["review"][10]

'phil  alien  one   quirky films   humour  based around  oddness  everything rather  actual punchlinesat first    odd  pretty funny    movie progressed  didnt find  jokes  oddness funny anymoreits  low budget film thats never  problem      pretty interesting characters  eventually   lost interesti imagine  film would appeal   stoner   currently partakingfor something similar  better try brother  another planet'

In [ ]:
test=remove_stopwords(df["review"][10])
test

'phil alien one quirky films humour based around oddness everything rather actual punchlinesat first odd pretty funny movie progressed didnt find jokes oddness funny anymoreits low budget film thats never problem pretty interesting characters eventually lost interesti imagine film would appeal stoner currently partakingfor something similar better try brother another planet'

In [ ]:
" ".join(set(df["review"][10].split()).symmetric_difference(set(test.split())))

''

remove_emoji handle

In [ ]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [ ]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [ ]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [ ]:
!pip install emoji

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x102834690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/emoji/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1028523d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/emoji/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1028685d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/emoji/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10280e750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/emoji/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10285fb90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/emoji/
ERROR: Could not find a version that satisfies the requirement emoji (from versions: none)
ERROR: No matching distribution found for emoji

In [ ]:
# show notebook kernel/python path (pure Python)
import sys
print(sys.executable, sys.version)

/Users/syedadilejaz/anaconda3/bin/python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

In [ ]:
# run the same as a shell command from the notebook kernel
!python -c "import sys; print(sys.executable, sys.version)"

/Users/syedadilejaz/anaconda3/bin/python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

In [ ]:
# install emoji into the exact kernel interpreter (preferred for notebook)
import sys
!{sys.executable} -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org emoji

Collecting emoji
  Obtaining dependency information for emoji from https://files.pythonhosted.org/packages/e1/5e/4b5aaaabddfacfe36ba7768817bd1f71a7a810a43705e531f3ae4c690767/emoji-2.15.0-py3-none-any.whl.metadata
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 2.3 MB/s eta 0:00:0000:0100:01m
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [ ]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

Tokenization

1. Using the split function

In [ ]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [ ]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [ ]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

2. Regular Expression

In [ ]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

3. NLTK

In [ ]:
# ...existing code...
import nltk
nltk.download('punkt_tab', quiet=True)   # ensure punkt is available
from nltk.tokenize import word_tokenize, sent_tokenize

sent1 = 'I am going to visit delhi!'
print(word_tokenize(sent1))
# ...existing code...

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [ ]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [ ]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [ ]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [ ]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

4. Spacy (good)

In [ ]:
!pip3 install spacy

Requirement already satisfied: spacy in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.24.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (68.0.0)
Requirement already satisfied: packaging>=20.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (23.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from jinja2->spacy) (2.1.1)
Requirement already satisfied: anyio in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (3.5.0)
Requirement already satisfied: httpcore==1.* in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.2.0)

In [ ]:
%pip install -U typing_extensions spacy

Requirement already satisfied: typing_extensions in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (4.15.0)
Requirement already satisfied: spacy in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.19.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (1.24.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.31.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (68.0.0)
Requirement already satisfied: packaging>=20.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from spacy) (23.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from jinja2->spacy) (2.1.1)
Requirement already satisfied: anyio in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (3.5.0)
Requirement already satisfied: httpcore==1.* in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /Users/syedadilejaz/anaconda3/lib/python3.11/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import sys 
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 6.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

NameError: name 'sent5' is not defined

In [ ]:
doc4 = nlp(sent1)
doc4

NameError: name 'nlp' is not defined

In [ ]:
for token in doc4:
    print(token)

NameError: name 'doc4' is not defined

In [ ]:
df.head()

,review,sentiment,review_fixed,review_fixed_spell
0,one reviewers mentioned watching 1 oz e...,positive,one of the other reviews has mentioned that af...,one of the other reviews has mentioned that af...
1,wonderful little production filming techniqu...,positive,a wonderful little production the filling tech...,a wonderful little production the filling tech...
2,thought wonderful way spend time hot s...,positive,i thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,basically theres family little boy jake thi...,negative,basically there a family where a little boy ja...,basically there a family where a little boy ja...
4,petter matteis love time money visually s...,positive,letter matters love in the time of money is a ...,letter matters love in the time of money is a ...

Stemmer

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:

ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [ ]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [ ]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

Lemmatization

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/syedadilejaz/nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/syedadilejaz/nltk_data...

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - '/Users/syedadilejaz/nltk_data'
    - '/Users/syedadilejaz/anaconda3/nltk_data'
    - '/Users/syedadilejaz/anaconda3/share/nltk_data'
    - '/Users/syedadilejaz/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

NOTE: Stemming & lamatization are same to retrieve root words but lamatization is worked good. Lamatization is slow & stemming is fast